Bump ttbox to 0f3e5fd
This ttbox version bump pins its Python to Python 2.7 and thereby
avoids running with Python 3, which would cause errors as:

ModuleNotFoundError: No module named 'gme_raw_chunk'

Fixes #4